spring.application.name=inventoryManager

spring.datasource.url=jdbc:postgresql://localhost:5432/inventorymanager
spring.datasource.username=postgres
spring.datasource.password=Dabgaryan200$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
